version: '3.8'
services:
  app:
    build:
      context: ./
      target: base
    working_dir: /usr/src/app
    command: ['yarn', 'run', 'dev']
    ports:
      - '3000:3000'
    volumes:
      - './:/usr/src/app'
      - './.cache/yarn:/root/.cache/yarn'

  storybook:
    build:
      context: .
      target: base
    working_dir: /usr/src/app
    command: ['yarn', 'workspace', '@apps/storybook', 'run', 'storybook:dev']
    ports:
      - '6006:6006'
    volumes:
      - './:/usr/src/app'
      - './.cache/yarn:/root/.cache/yarn'
